CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, message VARCHAR(255) NOT NULL, created DATETIME DEFAULT NULL, updated DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', available_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', delivered_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', expires_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id);

ALTER TABLE user ADD active TINYINT(1) DEFAULT 1 NOT NULL;

ALTER TABLE user ADD deleted TINYINT(1) NOT NULL;

CREATE TABLE user_order (id INT AUTO_INCREMENT NOT NULL, billing VARCHAR(255) NOT NULL, shipping VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE user_order ADD user_id INT NOT NULL;
ALTER TABLE user_order ADD CONSTRAINT FK_17EB68C0A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id);
CREATE INDEX IDX_17EB68C0A76ED395 ON user_order (user_id);

ALTER TABLE user_order RENAME INDEX fk_17eb68c0a76ed395 TO IDX_17EB68C0A76ED395;

CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE product ADD referance VARCHAR(255) NOT NULL;

ALTER TABLE product
ADD UNIQUE (reference);

CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE product ADD category_id INT NOT NULL;
ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id);
CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id);

CREATE TABLE ring (id INT AUTO_INCREMENT NOT NULL, size VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE ring ADD product_id INT NOT NULL;
ALTER TABLE ring ADD CONSTRAINT FK_8FDCF5764584665A FOREIGN KEY (product_id) REFERENCES product (id);
CREATE UNIQUE INDEX UNIQ_8FDCF5764584665A ON ring (product_id);

ALTER TABLE ring DROP INDEX FK_8FDCF5764584665A, ADD UNIQUE INDEX UNIQ_8FDCF5764584665A (product_id);

ALTER TABLE ring ADD stonetype VARCHAR(255) NOT NULL, ADD style VARCHAR(255) NOT NULL;

ALTER TABLE ring ADD weight NUMERIC(10, 0) NOT NULL;

CREATE TABLE bracelete (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE product ADD price NUMERIC(5, 0) NOT NULL;

ALTER TABLE product ADD created DATETIME DEFAULT NULL, ADD updated DATETIME DEFAULT NULL;
ALTER TABLE product CHANGE status status TINYINT(1) DEFAULT 1 NOT NULL;

ALTER TABLE bracelete ADD length NUMERIC(10, 2) NOT NULL, ADD braceletetype VARCHAR(255) NOT NULL, ADD adjustable TINYINT(1) NOT NULL;

ALTER TABLE bracelete ADD product_id INT NOT NULL;
ALTER TABLE bracelete ADD CONSTRAINT FK_C1FD81AC4584665A FOREIGN KEY (product_id) REFERENCES product (id);
CREATE UNIQUE INDEX UNIQ_C1FD81AC4584665A ON bracelete (product_id);

ALTER TABLE product ADD UNIQUE (reference);

DROP INDEX referance ON product;

CREATE TABLE employee (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, mobile VARCHAR(20) NOT NULL, department VARCHAR(255) DEFAULT NULL, salary DOUBLE PRECISION DEFAULT NULL, active TINYINT(1) NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE employee ADD user_id INT NOT NULL;
ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id);

CREATE UNIQUE INDEX UNIQ_5D9F75A1A76ED395 ON employee (user_id);

CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON employee (email);

ALTER TABLE employee CHANGE user_id user_id INT DEFAULT NULL;

ALTER TABLE employee ADD email VARCHAR(255) NOT NULL, ADD password VARCHAR(255) NOT NULL, ADD role JSON NOT NULL;

CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, filename VARCHAR(255) NOT NULL, ismain TINYINT(1) NOT NULL, sorting INT NOT NULL, INDEX IDX_C53D045F4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;

ALTER TABLE image ADD CONSTRAINT FK_C53D045F4584665A FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE image CHANGE ismain ismain TINYINT(1) DEFAULT NULL, CHANGE sorting sorting INT DEFAULT NULL;
